### ISSUE TITLE
I. Export du porfolio étudiant en PDF

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/karuta-APC#10]
Imprimer le portfolio par l’étudiant : afficher tout le portfolio dans une seule page donc impression en PDF : fureteur qui gère mais intégrer des sauts de page pour KAPC 1.3 et envisager un rapport de synthèse pour 1.3-1 ? Julien : aller plus loin dans un système de mapping pour la version industrielle ou KAPC 1.4 ?

lié à l'issue #8 et #9, revient à créer une nouvelle xsl

**Comment by jgribonvald** [comment]
à voir peut-être dans #57

**Comment by AdrienPrugnaud** [comment]
En cours, premier export en PDF page par page fait et en attente pour un export plus détaillé et complet
