### ISSUE TITLE
Possibilité de soumettre les actions des étudiants hors migration

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/karuta-APC#102]
Demande d'Eric : Création d'un script qui permet de figé les actions des étudiants.

**Comment by AdrienPrugnaud** [comment]
A l'issu du test il faudra préciser de vider la tableau des vecteurs car les demandes d'évaluations et de feedbacks des étudiants restent dans le tableau de bord des enseignants même après le passage du script

**Comment by jgribonvald** [comment]
Manque doc dans  "Soumettre les pages actions des portfolios étudiants"
il faudrait ajouter les indications sur comment vider la ou les tables de vecteur après cette opération et indiquer  un texte type "Attention cette opération figera les SAés et fera disparaître les demandes d'évaluations ainsi que les demandes de feedback des tableaux de bords des évaluateurs. Il est recommandé de ne pas le faire en cours d'année"

**Comment by AdrienPrugnaud** [comment]
Ton script de soumissions des actions permettais aussi bien de figer les actions que de vider la table des vecteurs peut importe si c'était une demande d'évaluation, de feedback... ? Car il reste une demande de feedback qui ne part pas (voir pj "Batch de soumission"). J'ai aussi retesté le batch est certaines demandes ne sont pas supprimés (voir pj). C'est toujours le cas pour les demandes concernant les compétences personnalisées. En tout cas les actions sont bien soumises.

A retester ?

**Comment by AdrienPrugnaud** [comment]
il reste le fait que les demandes de feedbacks concernant les compétences personnalisées reste

**Comment by jgribonvald** [comment]
Ce n'est pas la même chose que les pages actions, là ça concerne les compétences. => À voir plus tard
