### ISSUE TITLE
Trace non transférable d'une collection de trace vers hors collection

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/karuta-APC#107]
Le problème de déplacer une trace d'une collection vers le hors collection est réapparu (voir pj "Erreur déplacer trace hors collection")

**Comment by jgribonvald** [comment]
En fait cela est corrigé mais fonctionnel uniquement pour les nouveaux portfolios et pas pour ceux migrés, c'est assez compliqué à réaliser sur les anciens portfolios.
