### ISSUE TITLE
Problème SAés migrés, rajout en double de composantes essentielles...

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/karuta-APC#108]
Sur les SAés déjà créés et migrées l'enseignant peut rajouter de nouveau les composantes essentielles, les situations pro... qu'il a déjà ajouté (voir pj Saé déjà créé)

**Comment by AdrienPrugnaud** [comment]
Olivier dit qu'il faudrait passer un batch pour changer tous les menus. Il faut en rediscuter avec lui (question déjà soumise dans le mail du 20/10)

**Comment by olivier-gerbe** [comment]
Je viens de déposer une nouvelle version de migration 1.3 -> 1.3.5
J'ai ajouté au batch de migration des SAÉs de l'étape 4, la modification des menus pour ne pas avoir de doublons et j'ai ajouté une étape 4a pour l'exécution d'un batch pour ceux qui ont déjà fait les migrations.

**Comment by AdrienPrugnaud** [comment]
C'est corrigé
