### ISSUE TITLE
J. Traces sous les questions des pages actions

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/Karuta-APC#11]
(Dé)Placer les traces sous les questions dans les pages actions : la demande ne fait pas consensus actuellement pas KAPC 1.3

**Comment by jgribonvald** [comment]
Pourquoi pas si ce n'est pas compliqué et n'apporte pas de lourdeur à l'usage/au chargement.
Avis @olivier-gerbe

**Comment by isabelle-roy** [comment]
Les traces sont directement sous les questions actuellement. Je ne comprends pas la demande.

**Comment by jgribonvald** [comment]
abandonné
