### ISSUE TITLE
Problème rajout plusieurs fois les composantes essentielles et situation pro dans le portfolio étu

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/karuta-APC#110]
Le problème de pouvoir rajouter plusieurs fois les mêmes "Composantes essentielles prises en compte", "Situations professionnelles prises en compte" est toujours actif dans les portfolios étudiants (voir pj "Rajouter plusieurs fois des composantes essentielles"). Aussi bien pour les "Mes stages et alternances", "Mes autres actions"... Par contre il n'est plus présent dans les SAés et stages créées par les enseignants

**Comment by olivier-gerbe** [comment]
Je ne comprends pas bien. En principe les SAEs ont été soumises pendant la migration, on ne peut plus ajouter de composantes ou de compétences.

**Comment by AdrienPrugnaud** [comment]
Je reformule, aucun problème concernant les SAés par contre dans "Mes stages et alternances" et "Mes autres actions" l'étudiant pouvait rajouter x fois la même "Composantes essentielles prises en compte"...
Merci tu as corrigé
