### ISSUE TITLE
Batch pour fermer les demandes en cours côté apprenant après nettoyage table vector_table

### ISSUE THREAD

**Issue by jgribonvald** [avenirs-esr/karuta-APC#114]
La suppression des demandes dans la table vector_table ne permet pas de nettoyer les demandes faites par les étudiants, il faudrait un batch de migration qui permet de les fermer.

Cela fait suite aux bugs rencontrés, normalement nous ne devrions pas nous retrouver dans cet état.

**Comment by olivier-gerbe** [comment]
Oups! Je ne comprends pas. On parlait, je crois, d'un batch pour supprimer les demandes de feedback et d 'évaluation pour les compétences. Non?

**Comment by jgribonvald** [comment]
> Oups! Je ne comprends pas. On parlait, je crois, d'un batch pour supprimer les demandes de feedback et d 'évaluation pour les compétences. Non?

Oui c'est bien ça Olivier. Mais si ma description n'est pas bonne il faut m'expliquer. Toutes les demandes finissent bien dans la table vector_table ?

**Comment by olivier-gerbe** [comment]
Oui, toutes les demandes sont dans la table vector_table. C'est juste que cette issue n'est pas un bug. Si je comprends bien c'est une demande pour créer un batch qui soumettraient les demandes de feedback et d'évaluation pour les compétences et qui donc feraient disparaître les demandes en suspens de la table vector_table.

**Comment by jgribonvald** [comment]
@olivier-gerbe c'est lié à un bug, car suite aux bugs sur la version 1.3 le nettoyage de la table vector fait perdre le lien et donc la fermeture des demandes sur le PF de l'étudiant. Nous avons besoin d'un batch général pour faire le ménage lié au bug.

Ensuite je suis d'accord il y a des demandes autour de ce batch afin de pouvoir fermer les demandes (feedback, éval, etc..) en opération manuelle sur une formation, des étudiants listés, ou pour des compétences, situations et là c'est une demande fonctionnelle. Mais il faut que cela soit réalisé en même temps que le nettoyage de la table vector dans ce cas précis. Peut-être il serait bien qu'on reparle de cette fonctionnalité afin d'être tous bien d'accord sur le besoin.

**Comment by olivier-gerbe** [comment]
Ce batch et celui sur les SAÉs font justement le ménage. Ils soumettent toutes les demandes dans les portfolios étudiants et vident la table vector de ces demandes.

**Comment by AdrienPrugnaud** [comment]
Fait
