### ISSUE TITLE
Problème déplacer trace d'une collection de trace vers hors collection

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/karuta-APC#115]
Le déplacement d'une trace classée dans une collection vers le hors collection (même si la collection vient tout juste d'être créé) ne fonctionne pas

**Comment by olivier-gerbe** [comment]
Tu parles de portfolios tigrés?

**Comment by olivier-gerbe** [comment]
Comme déjà discuté. Pour les portfolios migrés, on ne peut pas remettre les traces dans Hors collection. Mais l'étudiant peut toujours créer une nouvelle collection et déplacer sa trace dedans si il veut la supprimer d'une collection donnée.

**Comment by AdrienPrugnaud** [comment]
On en avait discuté je remets ce sujet sur le tapis car d'où vient ce problème ? Lors de précédentes versions du module de migration tu avais réussi à le corriger.

**Comment by olivier-gerbe** [comment]
Je ne pense pas avoir pu le corriger. Cela vient du fait que l'étudiant n'a pas le droit d'écrire dans la section Hors collection et ce n'est pas possible de lui donner ce droit car il n'y a pas le rôle étudiant dur le noeud.

**Comment by AdrienPrugnaud** [comment]
On a eu plusieurs issues sur le sujet #54 (en juin), #98  (corrigés il y a environ 2-3 semaines)... et ce problème était corrigé. Est-ce dû à une nouveauté ?

**Comment by olivier-gerbe** [comment]
Non, on parlait de KPAC1.3 ou 1.3.5 pas des portfolios migrés.

**Comment by jgribonvald** [comment]
@AdrienPrugnaud on en avait parlé lors de notre réunion du 25/10. Ce problème est connu, il ne touche que les portfolios migrés et ne sera pas corrigé car il y a des contournements.

**Comment by jgribonvald** [comment]
> Par contre, est-ce ce problème persiste avec les nouvelles versions lors de nouvelles migrations ? avis @olivier-gerbe @AdrienPrugnaud ?

Même si j'ai fermé l'issue j'aimerais avoir une réponse, d'où ma relance @olivier-gerbe @AdrienPrugnaud . Merci

**Comment by AdrienPrugnaud** [comment]
Je laisse Olivier répondre. Il m'avait dit que c'était impossible

**Comment by olivier-gerbe** [comment]
Pour les portfolios avant 1.3.5, quelque soient les migrations futures, le problème persistera. Est-ce que cela répond à la question ?

**Comment by jgribonvald** [comment]
Merci Olivier, cela répond à ma question, dans le sens où les nouveaux portfolios ne rencontreront pas le problème à partir de la version 1.3.5.

**Comment by olivier-gerbe** [comment]
Exact. Les nouveaux n'auront pas de problèmes.
