### ISSUE TITLE
Problème doublon qui apparaissent dans hors collection

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/karuta-APC#116]
Un bug apparaît lors d'un choix d'une trace (dans une SAé ou autre), on peut voir les traces "hors collection" se retrouvent en doublon dans la nouvelle collection de trace (voir pj). La correction de ce bug ne peut pas attendre une 1.3.6.
![Uploading Doublon qui apparaissances dans une collection de trace.gif…]()

**Comment by olivier-gerbe** [comment]
Effectivement, il y a eu un oubli dans le batch de migration 1.3->1.3.5. C'est réparé.

**Comment by AdrienPrugnaud** [comment]
Fait
