### ISSUE TITLE
Apparition du portfolio d'Olivier en designer

### ISSUE THREAD

**Issue by GhisDUGAT** [avenirs-esr/karuta-APC#117]
De temps en temps (des fois plus souvent que d'autres), le portfolio d'Olivier apparaît lorsque nous utilisons Karuta en tant que designer.

**Comment by AdrienPrugnaud** [comment]
C'est sans doutes un problème de rôle ou d'attribution des portfolios. Tu peux supprimer son compte et le recréer cela peut résoudre le problème

**Comment by GhisDUGAT** [comment]
En vrai il n'y a pas que le portfolio d'Olivier, des fois c'est juste la dernière page que j'ai visité...

**Comment by AdrienPrugnaud** [comment]
As-tu des captures d'écrans pour illustrer stp ?
