### ISSUE TITLE
Crayon non cliquable sur une fiche de stage

### ISSUE THREAD

**Issue by GhisDUGAT** [avenirs-esr/karuta-APC#118]
![Petit crayonb](https://github.com/avenirs-esr/karuta-APC/assets/137498177/1741087a-15e2-4a06-9e68-00174b9ca2ae)
Lorsque l'on donne la possibilité à l'étudiant d'éditer le logo de son stage, le crayon apparait mais il n'est pas cliquable. Le Problème vient du fichier kapc-1-3-5.css, à la ligne 235, il faut enlever les sélecteurs suivants :
.page-action-stage .image-gauche .resource-node,
.page-action-autre .image-gauche .resource-node

**Comment by AdrienPrugnaud** [comment]
As-tu réussi à résoudre le problème ? Sinon il faut voir avec Olivier car c'est de la customisation et je ne peux pas t'aider

**Comment by GhisDUGAT** [comment]
Oui chez moi j'ai résolu le problème mais je l'ai mis là parce que je pense que ça concerne tout le monde
