### ISSUE TITLE
K. Sélection multiples de traces par l'étudiant

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/Karuta-APC#12]
Les étudiants demandent à pouvoir, quand ils associaient des traces dans une saé ou dans une autre action, de pouvoir sélectionner plus facilement les traces (EG : utiliser les collections dans le choix de traces depuis une sae = ne marche que si l’étudiant renseigne les codes uniques pour les traces et collections ? à vérifier / étudier la faisabilité Olivier, dernier choix : une fonction recherche où l’étudiant tappe un mot ?, trier les traces par plus récent au plus ancien donc code auto par l’heure => possible)

**Comment by isabelle-roy** [comment]
Olivier a ajouté un bouton Select All dans tous les imports multiples de Karuta.

**Comment by olivier-gerbe** [comment]
C'est fait. À tester
