### ISSUE TITLE
M. Figer/défiger le contenu de la SAé lors de la demande d’évaluation par l’enseignant

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/karuta-APC#14]
Bloquer le contenu de la saé une fois que la demande d’évaluation est envoyée par l’étudiant, l’enseignant doit pouvoir la « remettre en évaluation » KAPC 1.3 
Version industrielle = imaginer que l’étudiant puisse débloquer la saé tant que l’enseignant n’a pas déclarer commencer l’évaluation (en une fois par l’enseignant pour toutes les demandes d’une même saé)

**Comment by giraudin** [comment]
Côté étudiant le contenu de la saé se fige bien après demande d'évaluation mais par contre l'enseignant ne peut pas la remettre en édition si il veut que l'étudiant la retravaille.

**Comment by giraudin** [comment]
Dans 1.3 un enseignant ne peut pas remettre en édition une action (saé, etc.). Un compte resetter peut être donné par l'administrateur à un groupe d'usagers (cohorte).

**Comment by jgribonvald** [comment]
à vérifier avec e-portfolium @olivier-gerbe

**Comment by olivier-gerbe** [comment]
Je pense que Julien a ajouté dans le code, la possibilité de mettre le rôle enseignant pour remettre en édition. Il suffirait alors de mettre à jour les métadonnées.

**Comment by jgribonvald** [comment]
À vérifier.

**Comment by olivier-gerbe** [comment]
Dans la dernière version du backend, on peut mettre n'importe quel rôle pour réinitialiser. Il faudrait qualifier puis ajouter le rôle enseignant pour réinitialiser dans tous les modèles : sae , stages, ...

**Comment by jgribonvald** [comment]
@GhisDUGAT pourrais tu vérifier cela ?

**Comment by AdrienPrugnaud** [comment]
Testé avec la nouvelle livraison. Fait et à confirmer par Ghislain

**Comment by GhisDUGAT** [comment]
Bonjour @AdrienPrugnaud et @jgribonvald , désolé de revenir vers vous si tard mais je ne trouve pas le bouton pour réinitialiser la SAé.

Voici les versions des composants utilisés :
Karuta-frontend : 3.12.2 (2023-10-04T21:13:40Z)
Karuta-backend : 2.6.3 (2023-09-27T13:11:50Z)
Karuta-fileserver : 1.3.0 (2022-09-19T12:05:59Z)


![Détail SAe](https://github.com/avenirs-esr/karuta-APC/assets/137498177/c697f0f4-02d6-4d6a-bd93-d3d25667078b)



![Liste des SAes](https://github.com/avenirs-esr/karuta-APC/assets/137498177/fcba3a9d-ff7f-437f-b1cd-4decf35832a4)

**Comment by jgribonvald** [comment]
e-portfolium ( @olivier-gerbe ou Jacques) va fournir des copies d'écrans du déroulé pour obtenir les boutons
e-portoflium va revenir vers @GhisDUGAT pour voir ce qui se passe

**Comment by AdrienPrugnaud** [comment]
A valider par @GhisDUGAT

**Comment by GhisDUGAT** [comment]
Bonjour,

C'est toujours un No Go pour nous. @AdrienPrugnaud on peut s'appeler pour en discuter si tu veux.

**Comment by giraudin** [comment]
Ghislain,
Tu peux essayer si mon astuce fonctionne en désigner car pour moi elle ne fonctionne pas dans certains cas. Je n'explique pas pourquoi même en désigner il est impossible de Défiger une sae.

⁣Télécharger TypeApp pour Android ​

Le 7 nov. 2023, 09:50, à 09:50, Eric Giraudin ***@***.***> a écrit:

**Comment by GhisDUGAT** [comment]
Je ne vois pas le bouton Réévaluer après avoir dépublié la SAé...

**Comment by giraudin** [comment]
En designer ? La sae a été finalisée avant ?

⁣Télécharger TypeApp pour Android ​

Le 7 nov. 2023, 10:32, à 10:32, GhisDUGAT ***@***.***> a écrit:

**Comment by GhisDUGAT** [comment]
Non. Tu peux me donner les étapes précises à réaliser pour tester ta procédure stp ?

**Comment by giraudin** [comment]
1) un étudiant soumet une sae dans son portfolio pour évaluation à un enseignant 
2) l'enseignant depuis son portfolio ou tableau de bord clique sur la demande d'évaluation et clique sur finaliser
3) en tant que désigner tu vas sur la sae en question directement sur le portfolio de l'étudiant
4) tu depublies
5) tu cliques sur le bouton Réévaluer 
6) tu cliques sur publier
7) tu restes en désigner et tu prends le rôle étudiant et tu regardes si la sae  n'est plus figée 

⁣Télécharger TypeApp pour Android ​

Le 7 nov. 2023, 10:46, à 10:46, GhisDUGAT ***@***.***> a écrit:

**Comment by GhisDUGAT** [comment]
Effectivement je vois bien le bouton réévaluer, cependant il ne fonctionne pas. (La Saé reste évaluée et l'étudiant ne peut plus redemander une évaluation)

**Comment by giraudin** [comment]
OK merci ça confirme mon pb, j'ai le même et bizarrement pour certains cas ça marche, ce que je n'explique pas

⁣Télécharger TypeApp pour Android ​

Le 7 nov. 2023, 11:01, à 11:01, GhisDUGAT ***@***.***> a écrit:

**Comment by AdrienPrugnaud** [comment]
Bonjour à tous,

Je remets ce que j'ai mis tout à l'heure dans le rocketchat (en pj)

Cordialement,
Adrien

Le Mardi 7 Novembre 2023 10:56 CET, Eric Giraudin ***@***.***> a écrit:
 
 1) un étudiant soumet une sae dans son portfolio pour évaluation à un enseignant
2) l'enseignant depuis son portfolio ou tableau de bord clique sur la demande d'évaluation et clique sur finaliser
3) en tant que désigner tu vas sur la sae en question directement sur le portfolio de l'étudiant
4) tu depublies
5) tu cliques sur le bouton Réévaluer
6) tu cliques sur publier
7) tu restes en désigner et tu prends le rôle étudiant et tu regardes si la sae  n'est plus figée

⁣Télécharger TypeApp pour Android ​

Le 7 nov. 2023, 10:46, à 10:46, GhisDUGAT ***@***.***> a écrit:
>Non. Tu peux me donner les étapes précises à réaliser pour tester ta
>procédure stp ?
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/avenirs-esr/karuta-APC/issues/14#issuecomment-1798150718
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***> 


--

 Adrien PRUGNAUD / Chargé de mission ePortfolio
Port. +33 (0)6 49 17 61 ***@***.***

GIP Recia · Ressources numériques publiques en Centre-Val de Loire
Antenne de Touraine · 4-6, boulevard de Chinon · 37510 BALLAN-MIRÉ
Tél. 02 38 42 79 60
www.recia.fr ·

**Comment by AdrienPrugnaud** [comment]
Bonjour à tous,

J'ai mis des captures d'écrans dans le rocketchat esup.

Cordialement,
Adrien

Le Mardi 7 Novembre 2023 10:56 CET, Eric Giraudin ***@***.***> a écrit:
 
 1) un étudiant soumet une sae dans son portfolio pour évaluation à un enseignant
2) l'enseignant depuis son portfolio ou tableau de bord clique sur la demande d'évaluation et clique sur finaliser
3) en tant que désigner tu vas sur la sae en question directement sur le portfolio de l'étudiant
4) tu depublies
5) tu cliques sur le bouton Réévaluer
6) tu cliques sur publier
7) tu restes en désigner et tu prends le rôle étudiant et tu regardes si la sae  n'est plus figée

⁣Télécharger TypeApp pour Android ​

Le 7 nov. 2023, 10:46, à 10:46, GhisDUGAT ***@***.***> a écrit:
>Non. Tu peux me donner les étapes précises à réaliser pour tester ta
>procédure stp ?
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/avenirs-esr/karuta-APC/issues/14#issuecomment-1798150718
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***> 


--

 Adrien PRUGNAUD / Chargé de mission ePortfolio
Port. +33 (0)6 49 17 61 ***@***.***

GIP Recia · Ressources numériques publiques en Centre-Val de Loire
Antenne de Touraine · 4-6, boulevard de Chinon · 37510 BALLAN-MIRÉ
Tél. 02 38 42 79 60
www.recia.fr ·

**Comment by AdrienPrugnaud** [comment]
Fait
