### ISSUE TITLE
O. Remontée des étudiants qui ont demandé ou non une évaluation

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/karuta-APC#16]
L’enseignant a besoin de voir par SAé, stage ou alternance quels sont ceux qui ont demandé une évaluation et ceux qui ne l’ont pas fait 
=> Afficher ceux qui n’ont pas de date de demande d’évaluation sur une action (saé où l’enseignant s’est déclaré évaluateurs donc pas par l’enseignant) précise ? Ca va être long mais moins long que si un acteur externe admin le fait manuellement = > ça va traiter les portfolio qui sont partagés avec lui ? A étudier KAPC 1.3-1 / rapports différés à réétudier.

**Comment by jgribonvald** [comment]
avis e-portfolium version de faisabilité @olivier-gerbe 
On a compris que c'était compliqué, mais c'est demandé

**Comment by olivier-gerbe** [comment]
Comme les portfolios ne sont plus partagés automatiquement avec les enseignants. Pour un enseignant donné, on ne connait pas ses étudiants.

**Comment by AdrienPrugnaud** [comment]
Pas possible
