### ISSUE TITLE
A. RGPD et extraction données

### ISSUE THREAD

**Issue by jgribonvald** [avenirs-esr/karuta-APC#2]
Extraire les données de l’utilisateur pour supprimer les comptes et les données d’un portfolio
Pour extraire il est possible de faire un zip du portfolio qui contient tout - mais à voir plus tard pour faire mieux, cf #3 
La problématique est plus concernant la suppression de la totalité des données après sauvegarde, il faut supprimer le compte et toutes les données liées au compte. Là où il faut agir principalement c'est sur les données stockées sur le file-server, à moins qu'il y ait autrechose en plus à réaliser ?

Question RGPD: quel délai de conservation une fois que l'utilisateur est parti du contexte ? 3 ans de conservation ? propre à chaque établissement, donc configurable

**Comment by AdrienPrugnaud** [comment]
Pour l'instant extraction en PDF + conservation des données selon les établissements (ex Tours 3 mois)
