### ISSUE TITLE
JJ.	Alerter l’étudiant quand il modifie une trace

### ISSUE THREAD

**Issue by giraudin** [avenirs-esr/Karuta-APC#37]
Informer l’étudiant que s’il modifie un lien ou un fichier dans un trace qu’il faudra qu’il supprime la trace dans la page action telle qu’une saé sinon le lien depuis la page saé vers le fichier dans la trace ne fonctionnera plus

**Comment by olivier-gerbe** [comment]
Une bulle d'aide expliquera comment faire si on change le libellé de la trace.

**Comment by jgribonvald** [comment]
@AdrienPrugnaud pourquoi cette ré-ouverture ?

**Comment by AdrienPrugnaud** [comment]
Fait
