### ISSUE TITLE
Faire revalider les CGU modifiées

### ISSUE THREAD

**Issue by jgribonvald** [avenirs-esr/Karuta-APC#44]
Il faudrait apporter une solution à cette problématique quand les CGU changent pour les faire revalider aux utilisateurs.

**Comment by AdrienPrugnaud** [comment]
Demande appuyée par l’IUT de Lyon 1

**Comment by jgribonvald** [comment]
avis e-portfolium @olivier-gerbe 

taguer avec date de publication les CGU, et changer cette date à chaque changement pour comparer dans les portfolios la dernière date de CGU validée

**Comment by olivier-gerbe** [comment]
Il suffirait de passer un batch pour désoumettre les CGU ou alors (plus compliqué) indiquer quelque part la nouvelle date et tester à l'ouverture du portfolio par l'étudiant.

**Comment by olivier-gerbe** [comment]
Fait

**Comment by olivier-gerbe** [comment]
Il ya un batch pour remplacer les CGU.
