### ISSUE TITLE
Perte de rôle de l'étudiant quand il clique sur un lien Pair/Tuteur sur évaluation

### ISSUE THREAD

**Issue by jgribonvald** [avenirs-esr/Karuta-APC#46]
Il s'agit d'un problème de gestion de session, on ne devrait pas accéder à un lien unique externe (sans authentification) alors qu'on a une session ouverte.

**Comment by jgribonvald** [comment]
la solution serait d'interdire l'accès aux liens directs quand une session est existante et non échue. Proposer une page de déconnexion pour continuer l'accès dans ce cas. Action principalement backend.

**Comment by olivier-gerbe** [comment]
À priori, si l'étudiant a perdu le rôle étudiant sur son portfolio, c'est parce qu'il s'est demandé une évaluation par pair/ ouuteur sur son portfolio. Il se retrouve donc avec son propre portfolio partagé comme étudiant et pair ou tuteur.

**Comment by jgribonvald** [comment]
Fix à mettre en place: Vérifier que l'adresse mail d'envoi n'est pas celle du compte étudiant et si = mettre un message

**Comment by isabelle-roy** [comment]
Fait - à valider par le RECIA
