### ISSUE TITLE
Paramètres de tri avancés des évaluations 

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/Karuta-APC#48]
#6 pour continuer les avancées au niveau des possibilités de tri il faudrait permettre aux enseignants dans leur tableau de bord de sélectionner seulement une SAé en particulier, ou une compétence, un stage... et étudier une piste javascript tri multi sélection pour voir si le cumul de tri est possible

**Comment by jgribonvald** [comment]
/cc @olivier-gerbe 
Désolé Olivier je te retire des assignees temporairement, le temps qu'on statue sur la fonctionnalité (il faut qu'on voit avec vous aussi via une réunion).

**Comment by jgribonvald** [comment]
@AdrienPrugnaud peux tu vérifier le fonctionnement ? il faut qu'on documente aussi...

**Comment by jgribonvald** [comment]
fait mais #103 et #104 (bug et doc) pour finir
