### ISSUE TITLE
Changer la dénomination des portfolios enseignants

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/Karuta-APC#50]
Changer de "ePortfolio de nom de l'enseignant" en "Mon tableau de bord d'évaluateur" ce qui est plus parlant lorsqu'ils arrivent sur leur compte

**Comment by jgribonvald** [comment]
Il faut revoir le nommage afin d'afficher le nom de la personne sinon l'admin ne pourra pas retrouver le portfolio d'un enseignant en particulier, ils auront tous le même nom.

exemple de nom "Tableau de bord de NOM_PRENOM"

**Comment by isabelle-roy** [comment]
Fait KAPC 1.4, à tester par le RECIA
