### ISSUE TITLE
Lien vers une page de support en place d'un envoie mail

### ISSUE THREAD

**Issue by jgribonvald** [avenirs-esr/Karuta-APC#52]
Actuellement une icône mail permet d'envoyer un mail pour demander du support, l'adresse est préconfigurée et tout le monde ne pense pas à la changer.
L'idée est de remplacer ce comportement par défaut par le choix de configurer un simple lien URL à configurer.

**Comment by jgribonvald** [comment]
avis e-portfolium @olivier-gerbe (on avait commencé à en parler)

**Comment by olivier-gerbe** [comment]
C'est fait dans FEAT2023

**Comment by jgribonvald** [comment]
reste à merger
