### ISSUE TITLE
Déplacer les traces

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/Karuta-APC#54]
Permettre de déplacer une trace d'une collection dans la section "hors-collection" (dans la section où les traces ne sont pas classées)

**Comment by olivier-gerbe** [comment]
Je ne comprends pas. C'est déjà possible dans 1.3

**Comment by jgribonvald** [comment]
Il faut en discuter

**Comment by jgribonvald** [comment]
Problème de version du frontend
