### ISSUE TITLE
Changer la taille des noms de SAés dans les bilans de compétences

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/Karuta-APC#55]
Mettre le nom des SAés plus en valeur dans la synthèse des apprentissages des bilans de compétences

![Image](https://user-images.githubusercontent.com/97050678/215805808-3f611cb2-3223-42ef-8e57-fe1cd13a2b48.jpg)

**Comment by jgribonvald** [comment]
Définir un nom court et avoir un nom long ou une description qui seront utilisés en fonction des différents affichage + Mettre en gros le nom court. Faire une distinction entre Nom des SAÉ et des compétences associées.

C'est plus de la mise en forme pour l'ensemble à revoir.

**Comment by giraudin** [comment]
Il faudrait également changer dans la page compétence le nom du bloc synthèse des apprentissages en :
"Synthèse des compétences et apprentissages développés pour chaque action menées"

**Comment by jgribonvald** [comment]
Pour une première étape: dans karuta faire sur les "tableaux éditables" un bouton plier/déplier des éléments sous les actions menées.

Et en 1.4 combiner les tableaux `récapitulatif des actions` et `synthèse des apprentissages`

**Comment by isabelle-roy** [comment]
@giraudin Est-ce que ça te convient ?
![image](https://user-images.githubusercontent.com/1541128/217871332-699999d7-aff6-48a4-9188-4a9454af2692.png)

**Comment by isabelle-roy** [comment]
Fait KAPC 1.3.5, à tester par le RECIA
