### ISSUE TITLE
Changement de nom bloc "Synthèse des apprentissages"

### ISSUE THREAD

**Issue by jgribonvald** [avenirs-esr/Karuta-APC#62]
Dans page compétences, changer le nom du bloc "synthèse des apprentissages" en "Synthèse des apprentissages développés pour chaque action menée".

**Comment by isabelle-roy** [comment]
**Synthèse des apprentissages critiques** de cette compétence renseignés lors de vos actions
Validé avec Éric.

**Comment by isabelle-roy** [comment]
Fait - à valider par le RECIA
