### ISSUE TITLE
Création d'une formation : ajout du partage du référentiel de compétences avec un compte utilisateur dans le rôle Responsable

### ISSUE THREAD

**Issue by isabelle-roy** [avenirs-esr/Karuta-APC#66]
Certaines universités commences à utiliser KAPC avec d'autres formations que celles pour lesquelles les référentiels de compétences existent.
Il faudrait ajouter un champ sur la page _Créer un programme de formation_ des portfolios _Quickstart_ et _Formulaires_ pour le login de la personne responsable de renseigner le référentiel de compétences vierge (le cas échéant) et ajouter le partage dans le batch.
v1.3.5 ??

**Comment by jgribonvald** [comment]
Isabelle, sur le principe on est d'accord, par contre il faut également pouvoir exporter le référentiel spécifique à une formation et il faudra qu'on voit comment on l'importe dans le référentiel commun et partagé.

**Comment by isabelle-roy** [comment]
De la même manière que n'importe quel autre référentiel, c'est le même modèle.

**Comment by isabelle-roy** [comment]
Fait
