### ISSUE TITLE
SAés et demandes de feedback fantômes

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/Karuta-APC#68]
Nous venons de réinstaller la 1.3 de KAPC+ et je viens de reconstater un problème déjà identifié :
les demandes d'évaluations et de feedbacks fantômes sont toujours présentes (dans mes souvenirs j'avais déjà testé et vous aviez résolu le problème).
Par exemple quand un étudiant supprime une SAé alors qu'il a fait une demande d'évaluation à un enseignant la SAé disparaît mais la demande d'évaluation est toujours présente dans le tableau de bord de l'enseignant (c'est la même chose pour les demandes de feedbacks). 
Ce qui est encore plus bizarre c'est que quelque fois la suppression fonctionne correctement.

**Comment by jgribonvald** [comment]
Corrigé avec les modifications du schéma de la base
