### ISSUE TITLE
Cacher la flèche aux étudiants dans "Mes bilans par compétence "

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/karuta-APC#73]
Dans mes bilans par compétences l’étudiant peut aussi remonter les compétences de sa formation au dessus des tableaux de bord. Il faut cacher la flèche avec du css dans la page parent des bilans de compétences)

**Comment by isabelle-roy** [comment]
Fait par CSS dans KAPC 1.4
