### ISSUE TITLE
Le test des évaluateurs a été oublié sur toutes les pages actions et compétences avec possibilité d'ajout des évaluateurs

### ISSUE THREAD

**Issue by giraudin** [avenirs-esr/Karuta-APC#77]
Présent sur la 1.2 mais plus présent sur la 1.3.

Il s'agit d'un bug de la 1.3 à corriger pour la mises à jour 1.3 à 1.3.5 ?

**Comment by isabelle-roy** [comment]
C'est déjà fait ça
