### ISSUE TITLE
Problème de la durée de validité d'un lien de partage pour évaluation

### ISSUE THREAD

**Issue by giraudin** [avenirs-esr/karuta-APC#78]
Sur Kapc 1.3 Actuellement 500h est la durée par défaut d'un lien de partage pour évaluation soit environ 3 semaines. Si l'enseignant dépasse 500h avant d'évaluer une action d'un étudiant, avec les jumelles il n'accède pas à la page de l'étudiant et le portfolio enseignant plante, il se fig.

Solution : 

-  soit on a une variable qu'on peut modifier au niveau de chaque action à évaluer à renseigner par l'enseignant qui publie la saé
- soit on allonge par défaut de 3 mois la durée du lien de partage

**Comment by isabelle-roy** [comment]
Implique des changements dans les référentiels de compétences !

**Comment by isabelle-roy** [comment]
Fait KAPC 1.4 - à tester par le RECIA
