### ISSUE TITLE
la base de données de karuta se verrouille pendant l'update et le delete des objets et des actions ne s'effectuent pas

### ISSUE THREAD

**Issue by giraudin** [avenirs-esr/Karuta-APC#80]
Dans KAPC 1.3 la base de données de karuta se verrouille pendant update et le delete  des objets

Les problèmes se retrouvent sur les pages action, demande évaluation envoyée mais reste dans l’état à traiter, feedback tronqué et certains envoyés mais restent dans l’état à traiter, liste des feedbacks traités toujours vide.

Probablement réglage du moteur MariaDB (InnodB ou pas) soit mal fait soit pas fait : revoir en détail les attributs de création da le DB.

Lenteur durant l'update et le delete  des objets de la DB.

Le redémarrage du service MariaDB peut régler ces problèmes très temporairement. Par exemple, après un redémarrage, les demandes de feedback sont alors de nouveau bien visibles dans le portfolio évaluateur, dans les feedbacks traités.

**Comment by jgribonvald** [comment]
Retour à MyISAM
