### ISSUE TITLE
Supprimer dans le module APC (Mon portfolio de compétences) en page d'accueil le bloc Mon projet personnel de réussite

### ISSUE THREAD

**Issue by giraudin** [avenirs-esr/karuta-APC#85]
Il est écrit que 
Mon projet personnel de réussite serait développé dans une version future, hors cette partie est devenu le module optionnel Mon projet de vie à partir de la 1.4 de KAPC+ et il n'a pas été développé dans les versions précédentes, donc le supprimer il ne sert à rien. On passe donc en page d'accueil de KAPC+ à uniquement 3 blocs au lieu de 4 :
Mes formations et leurs référentiels, Mes actions et mes traces, Mes bilans par compétence.

**Comment by isabelle-roy** [comment]
Fait


![image](https://github.com/EsupPortail/KAPC/assets/1541128/b5ba0d04-37fd-403d-89ea-ef577bac8d23)
