### ISSUE TITLE
Rétablir la page proxy aide dans le module APC (Mon portfolio de compétences) dans la V 1.4

### ISSUE THREAD

**Issue by giraudin** [avenirs-esr/karuta-APC#86]
La page proxy aide a disparu du module initial de KAPC+ (Mon portfolio de compétences). 

Elle existe bien par contre dans le module Mon projet de vie.

Il faut bien une page aide différente pour chacun des deux modules pour l'étudiant. 

Pour l'enseignant, elle doit être unique car il n'aura qu'un portfolio.

Pour le conseiller interne on peut prendre la page proxy aide de l'enseignant. 

Sur la page aide enseignant / conseiller interne quand je la renseignerai je complèterai avec :

-  si vous êtes enseignant ....
- si vous êtes conseiller interne....

**Comment by isabelle-roy** [comment]
Proxy mis à jour

Attention il y a deux portfolios de proxys : 
- un avec les proxys pour les portfolios étudiants APC et les portfolios enseignants : projet KAPC 1.4
- un avec les proxys pour portfolios étudiants projet de vie et les conseillers internes de projet de vie : module Projet de vie.

Les deux instances de portfolios proxy se trouvent dans le Répertoire des proxys mais si tu veux modifier le contenu des pages tu dois aller dans les portfolis modèles :

- `kapc/6proxys.modele-repertoire-proxys`
- `kapc/9Aprojetpro/6proxys.modele-repertoire-proxys-pp`
