### ISSUE TITLE
Problèmes collection de traces supprimés

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/karuta-APC#92]
Quand on ajoute une trace dans un portfolio migré en 1.3.5 ses collections de traces disparaissent

**Comment by AdrienPrugnaud** [comment]
1- Version 1.3.5 :
Il reste des questions en cours mais elles pourront être voir ultérieurement, je rajouterais qu'il faudrait des tests d'autres personnes pour confirmer qui n'y a pas d'autres bugs :
- Oubli sur KAPC+ 1.3.5, quand on créer un portfolio enseignant avec le Quickstart on a bien "Tableau de bord de...", par contre quand on le créer avec les batchs on a toujours "ePortfolio de...".

Corrigé = Parfait


Celui-ci est un peu plus handicapant tout de même - Quand l'enseignant finalise l'évaluation d'un stage, d'une compétence, d'une SAé... Après finalisation de l'évaluation l'enseignant se retrouve sur un écran blanc + si on actualise la page le tableau apparaît bien mais on ne peut plus cliquer sur les chiffres et le menu en haut à droit disparaît. Il faut ressortir du portfolio puis revenir pour que tout fonctionne correctement.

Est-ce que tu peux me faire un exemple que je teste moi-même.

Oui tu peux tester avec marc.loire, je vais envoyer des demandes d'évaluation et tu pourras constater ce problème.

2- Module de migration : 
Question :
- J'ai réussi en tant que tuteur à donner une évaluation, par contre si l'enseignant finalise son évaluation je ne peux plus donner la mienne en tant que tuteur. Ainsi faut-il prévenir les étudiants avec une description dans "?" ou ce n'est pas la peine car la logique serait que l'enseignant attende le retour du tuteur avant de finaliser son évaluation.

Je n’ai pas de réponse. Il faudrait avoir le retour d'Eric, je vais lui demander = On ne change rien

En cours :
- J'ai aussi supprimé un enseignant évaluateur sur une compétence transversale rajoutée en 1.2, la suppression de l'enseignant est très lente et on doit faire un F5 pour qu'elle fonctionne sinon cela tourne dans le vide (cf pj "Suppression évaluateur compétence transversale").

En tant que quoi as-tu supprimé un enseignant. Est-ce que tu peux me faire un exemple ? J'ai refait le tests mais c'est beaucoup plus rapide (peut-être du à la migration ou au de l'étudiant portfolio)

- Le problème de transfert d'une trace d'une collection vers le hors collection est réapparu (cf pj "Transférer traces hors collection"). Je précise que la trace n'est pas utilisée ailleurs, c'est une trace nouvellement créée.

Bizarre. Effectivement l’erreur était toujours dans le modèle portfolio étudiant. Tu as réussi à corriger l'erreur ?

New - Dans la page "Mes bilans par compétences", "Compétences personnalisées" l'étudiant peut créer directement une compétence dans cette page de bilan (normalement les bilans n'ont pas cette fonctionnalité) le souci c'est que la compétence personnalisé n'est pas déplacée dans la page "Mon référentiel de compétences personnalisées" (là où normalement on doit créer les compétences perso) et reste dans la page bilan (voir pj  "Création de compétences dans la page Bilan"). Il faudrait sans doutes désactiver cette option pour limiter les problèmes.

Je n’ai pas réussi à reproduire avec adrien.eure.
Le bug se trouve en fait seulement dans les portfolio migrés, tu peux constater sur damien.marne/demonumerique

**Comment by AdrienPrugnaud** [comment]
- Dans les portfolios "Formulaires KAPC+" il reste des anciennes données pour "Créer un compte et portfolio enseignant" et "Associer un enseignant à une formation" (info de carrière sociale) je croyais que ces informations avaient été supprimées.

- Dans les stages et alternance, les autres actions et dans les SAés l'encart "Important" comporte des espaces manquants (voir pj)

**Comment by jgribonvald** [comment]
idem que #93

**Comment by AdrienPrugnaud** [comment]
Corrigé
