### ISSUE TITLE
Date de dépôt pour les pj dans les traces

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/Karuta-APC#93]
Pour t'aider voici une vidéo d'une parties des problèmes trouvés : https://pod.recia.fr/video/0150-pour-olivier/f4d47544666cf6d012485a6a4c54092cd6b6edc9f2e3606e1dd9395092343597/

- Début de la vidéo problème de cumul de rôle (donc on ne peut pas faire grand-chose)
- A partir de 3 min 40 c'est un problème important, malgré que la SAé/compétence soit soumise ou évaluée l'étudiant peut quand même changer la pj de la trace utilisé dans celle-ci. Ainsi il peut, s'il ne supprime pas la trace, modifier son contenu (ce qui est très problématique en cas de contestation de la note etc...).
La solution trouvée serait de mettre la date de dépôt de la trace (je précise, pas la date de création de la trace mais bien du dépôt de la pj). Est-ce que tu penses que c'est possible ?

**Comment by jgribonvald** [comment]
@AdrienPrugnaud peux tu renommer cette issue pour avoir un titre en corrélation avec le bug rencontré ?

quel est le status de ce pb ?

Si possible ne faire qu'une issue par pb, et quand on traite avec e-portfolium pointer sur l'issue, et marquer comme résolu une fois résolu.

Merci

**Comment by AdrienPrugnaud** [comment]
Date de dépôt ajoutée par Olivier
